### PR TITLE
add security context to travel demo

### PR DESCRIPTION
**Pull request by jmazzitelli**
add security context to travel demo
part of: https://github.com/kiali/kiali/issues/5426

### CODE REVIEW

**Comment by jmazzitelli** [comment]
still doesn't work:

```
message: 'pods "voyages-685bbffd7c-" is forbidden: unable to validate against
        any security context constraint: [provider "anyuid": Forbidden: not usable
        by user or serviceaccount, spec.initContainers[0].securityContext.runAsUser:
        Invalid value: 1337: must be in the ranges: [1000790000, 1000799999],
```

**Comment by jmazzitelli** [comment]
this will work once https://github.com/josunect/kiali/pull/2/files is merged into master

**Comment by jshaughn** [comment]
We're going to need this for all demos right?  Especially those used in the cypress tests.

**Comment by jmazzitelli** [comment]
Yes. This PR was only "part of" https://github.com/kiali/kiali/issues/5426

**Pull request merged**
