### PR TITLE
move demos to quay.io

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/3777

### CODE REVIEW

**Comment by jmazzitelli** [comment]
scale-mesh demo image was renamed to follow the convention of the other demos. When we merge this, we need to delete the old, obsolete image repo - this one: https://quay.io/repository/kiali/scale-mesh-demo

**Comment by jmazzitelli** [comment]
I installed all the demos, saw all the pods in all the namespaces are "Running" and all images have "quay.io" in them. So all looks good.

**Comment by jmazzitelli** [comment]
@prachiyadav @lucasponce will we be able to get this in before the end of the week? With each sprint release, I think we tend to get an uptick of interest in these demos. Would be nice for people to avoid the docker.io rate limiting problem when that happens.

**Comment by lucasponce** [comment]
@prachiyadav is out this week, I can review it tomorrow.
I liked this PR as it was a good one to test the demos and get familiar with whole process, but we'll merge to be ready before the release.

Sorry for the delay.

**Comment by lucasponce** [comment]
@jmazzitelli did you use the build.sh for pushing the images or you did manually ?

In build.sh helpers there are some login/push to the docker.io that may need a variable to point to the repo

```
${DORP} login docker.io
${DORP} push ${DOCKER_SERVER_TAG}
${DORP} push ${DOCKER_CLIENT_TAG}
```

These helpers are very primitive/basic no need to add a lot of code there, but perhaps those may need a change.

**Comment by jmazzitelli** [comment]
> did you use the build.sh for pushing the images or you did manually ?

I did use that build.sh to build and push, yes. That login command obviously is hardcoded to docker hub but it probably does not matter because if you push an image with quay.io as the hub, the docker push command will attempt to push to that hub (it requires that you already be logged in, and I am already logged in). But yes I think that command should be updated to be:

```
${DORP} login ${IMAGE_HUB}
```

I'll make that change. It is in several of the scripts.

**Comment by jmazzitelli** [comment]
OK, that commit https://github.com/kiali/demos/pull/31/commits/43599efd8d5a560f5e1432e821a28480180964d1 is in - simple change to now docker login to `${IMAGE_HUB}` rather than hardcoding `docker.io`.

**Review by lucasponce — APPROVED** [review]

**Comment by lucasponce** [comment]
Thanks for the changes @jmazzitelli !

@prachiyadav I'm going to merge this one, I've tested locally and it seems ok.

But feel free to take a look as well, I'd like if you get familiar with these demos as I'm sure that will help to QE for future tests.

**Pull request merged**
