### PR TITLE
Add bookinfo with VMs example

### PR DESCRIPTION
**Pull request by nrfox**
Adds an example project of deploying Istio/bookinfo/kiali on GCP. This is helpful in testing kiali with Istio deployments using `WorkloadEntry` or `ServiceEntry`.

~Most of this large diff is due to the istio helm charts being directly imported/used in this project.~

To test, checkout the branch locally and follow the [README](https://github.com/kiali/demos/pull/34/files#diff-e8780add5fb300efe57914e7845117e3e96c8dedee0397052855161b61d6d28b).

### CODE REVIEW

**Review by jmazzitelli — CHANGES_REQUESTED** [review]
The fact that you've included istio helm charts directly here tells me this demo is quickly going to rot on the vine as istio releases new versions and diverts.

Is there anyway you can write a script that can download the latest helm charts for the user? That way, 6 months from now when Istio has 1.12 or 1.13, this demo will pull those latest helm charts and you won't have a demo that is pinned on a EOL'd version of Istio.

**Comment by nrfox** [comment]
> The fact that you've included istio helm charts directly here tells me this demo is quickly going to rot on the vine as istio releases new versions and diverts.
> 
> Is there anyway you can write a script that can download the latest helm charts for the user? That way, 6 months from now when Istio has 1.12 or 1.13, this demo will pull those latest helm charts and you won't have a demo that is pinned on a EOL'd version of Istio.

I added a script to grab the latest charts. It gets called by terraform but can also be run standalone.

**Review by jmazzitelli — APPROVED** [review]
I didn't run this - most of this is all gobbledygook to me (I don't know what terraform is :) I'll assume it works. At least now I see a script that pulls down the latest helm charts. The rest I'll leave for someone else with more knowledge of this infrastructure to review if they so choose.

**Comment by nrfox** [comment]
@jmazzitelli pushed a small update to include prom configuration. This has been open awhile so if it looks good I'll go ahead and merge.

**Pull request merged**
