### PR TITLE
[OSSM-5715] build multi-arch containers

### PR DESCRIPTION
**Pull request by jmazzitelli**
This should work:

`make -f Makefile-multiarch push-multiarch`

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I can't get this to work, but it doesn't surprise me. For some reason I can never build multi-arch images.

This is what I get:

```
$ make -f Makefile-multiarch push-multiarch 
for arch in amd64 arm64; do \
	echo "Building client for arch [${arch}]"; \
	cd /home/jmazzite/source/kiali/demos/error-rates/client && CGO_ENABLED=0 GOOS=linux GOARCH=${arch} go build \
		-o /home/jmazzite/source/kiali/demos/error-rates/_output/go/bin/client-${arch} ; \
done
Building client for arch [amd64]
Building client for arch [arm64]
for arch in amd64 arm64; do \
	echo "Building server for arch [${arch}]"; \
	cd /home/jmazzite/source/kiali/demos/error-rates/server && CGO_ENABLED=0 GOOS=linux GOARCH=${arch} go build \
		-o /home/jmazzite/source/kiali/demos/error-rates/_output/go/bin/server-${arch} ; \
done
Building server for arch [amd64]
Building server for arch [arm64]
Preparing container image files
A valid version of 'docker buildx' is available: 0.11.2
'docker buildx' is enabled
Ensuring QEMU is set up for this Linux host
{
  "supported": [
    "linux/amd64",
    "linux/arm64",
    "linux/riscv64",
    "linux/ppc64le",
    "linux/s390x",
    "linux/386",
    "linux/arm/v7",
    "linux/arm/v6"
  ],
  "emulators": [
    "qemu-aarch64",
    "qemu-aarch64_be",
    "qemu-alpha",
    "qemu-arm",
    "qemu-armeb",
    "qemu-hexagon",
    "qemu-hppa",
    "qemu-loongarch64",
    "qemu-m68k",
    "qemu-microblaze",
    "qemu-microblazeel",
    "qemu-mips",
    "qemu-mips64",
    "qemu-mips64el",
    "qemu-mipsel",
    "qemu-mipsn32",
    "qemu-mipsn32el",
    "qemu-or1k",
    "qemu-ppc",
    "qemu-ppc64",
    "qemu-ppc64le",
    "qemu-riscv32",
    "qemu-riscv64",
    "qemu-s390x",
    "qemu-sh4",
    "qemu-sh4eb",
    "qemu-sparc",
    "qemu-sparc32plus",
    "qemu-sparc64",
    "qemu-xtensa",
    "qemu-xtensaeb"
  ]
}
Pushing client multiarch image to quay
docker buildx build --push --pull --no-cache --builder=demo-builder --platform=linux/amd64 --platform=linux/arm64 --tag=quay.io/kiali/demo_error_rates_client:v1 -f /home/jmazzite/source/kiali/demos/error-rates/_output/docker/Dockerfile-client /home/jmazzite/source/kiali/demos/error-rates/_output/docker
[+] Building 15.1s (4/4) FINISHED                                                                        docker-container:demo-builder
 => [internal] load build definition from Dockerfile-client                                                                       0.0s
 => => transferring dockerfile: 344B                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                 0.0s
 => => transferring context: 2B                                                                                                   0.0s
 => ERROR [linux/arm64 internal] load metadata for quay.io/centos/centos:8                                                       15.0s
 => ERROR [linux/amd64 internal] load metadata for quay.io/centos/centos:8                                                       15.0s
------
 > [linux/arm64 internal] load metadata for quay.io/centos/centos:8:
------
------
 > [linux/amd64 internal] load metadata for quay.io/centos/centos:8:
------
ERROR: failed to solve: failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head https://quay.io/v2/centos/centos/manifests/8: dial tcp: lookup quay.io on 10.2.32.1:53: read udp 172.17.0.2:56736->10.2.32.1:53: i/o timeout
make: *** [Makefile-multiarch:104: .push-multiarch-client] Error 1
```

**Comment by mkralik3** [comment]
I have got error from Dockerfile-client
```
Dockerfile-client:10
--------------------
   8 |     WORKDIR $CLIENT_HOME
   9 |     
  10 | >>> COPY client-${TARGETARCH} $CLIENT_HOME/client
  11 |     
  12 |     ENTRYPOINT ["/opt/client/client"]
--------------------
ERROR: failed to solve: failed to compute cache key: "/client-" not found: not found
```
it looks like TARGETARCH env is empty. 

When I explicitly defined TARGETARCH on the line before (9) 
```
ARG TARGETARCH
```
It works for me.

**Review by josunect — APPROVED** [review]
I haven't tested but looks good

**Review by aljesusg — APPROVED** [review]
LGFM

**Pull request merged**
